name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  compile:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: maven

      - name: Download Dependencies
        run: mvn dependency:go-offline

      - name: Build
        run: mvn clean package

  security-check:
    needs: compile
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: maven

      - name: Download Dependencies
        run: mvn dependency:go-offline

      - name: Run Trivy
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: fs
          format: table
          output: trivy-report.txt

      - name: Upload Trivy Report
        uses: actions/upload-artifact@v4
        with:
          name: trivy-report
          path: trivy-report.txt

      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2